fix: no change_type fails when change_type_map provided
Under the following conditions:
- commit_parser either does not have a capture group for change_type or
  change_type is None for other reasons
- change_type_map is provided

We get the following error:
```
TypeError: argument of type 'NoneType' is not iterable
```

This provides a default change_type which can also be mapped using the
change_type_map.